echo "               ${white}.:^~~~~~^:            "           
echo "           ${white}^7YG#&@@@@@@@&B57:        ""       ${magenta}dMMMMMP ${bmagenta}.dMMMb   dMP dMP           "
echo "        ${white}^JB@@@@@@@@@@@@@@@@@&G7.     ""        ${magenta}.dMP\" ${bmagenta}dMP\" VP  dMP dMP          "
echo "      ${white}^5@@@@@@@@@@@@@@@@@@@@@@@B7    ""      ${magenta}.dMP\"   ${bmagenta}VMMMb   dMMMMMP            "
echo "     ${white}J@@@@@@@@@@@@@@@@@@@@@@@@@@@5   ""    ${magenta}.dMP\"   ${bmagenta}dP .dMP  dMP dMP             "
echo "    ${white}5@@@@@@@@@@@@@@@@@@@@@@@@#B&B@~  ""   ${magenta}dMMMMMP  ${bmagenta}VMMMP\"  dMP dMP  ${byellow}dMMMMMP"
echo "   ${white}?@@@@@@@@@@@@@@@@@@@@@@@@&:J@~:.  "                           
echo "  ${white}.#@@@@@@@@@@@@@@@@@@@@@@@J^ JY:  "                     "${blue}Hardware: ${bblue}$(sysctl -n hw.model) ${blue}OS: ${bblue}$(sw_vers -productName) $(sw_vers -productVersion)" # Hardware and OS info"
echo " ${white}:P&&&@@@@@@@@@@@@@@@@#GBP~        "                     "${blue}CPU: ${bblue}$(sysctl -n machdep.cpu.brand_string) ${blue}Memory: ${bblue}$(sysctl hw.memsize | awk '{print $2/1073741824" GB RAM"}')"
echo " ${white}~!:::7B@@@@@##&@@@@#^.   #        "                     "${blue}User: ${bblue}$(whoami) ${blue}Shell: ${bblue}$(basename $SHELL)"  # User, Shell, and Uptime info
echo " ${white}?P ${red}♁${white} :@@@&~ ..^!YB#^ .          "         "${blue}Network: ${bblue}$(networksetup -getcomputername)" # Network and Brew packages info
echo " ${white}P&??. ~7B@&. ${red}.⛢.${white}  :7!           "         "${blue}Diskspace: ${bblue}$(df -h / | awk 'NR==2 {print $4 " available"}' | sed 's/Gi/GB/')"
echo "${white}:#&@B~7: \Y@~ .${red}\`${white}   .#@7          "        "${blue}Uptime: ${bblue}$(uptime | awk -F'up ' '{print $2}' | cut -d',' -f1-2)"
echo " ${white}:!PY5?  \`.G&5BBG7J7P@@7           "                    "${blue}Packages: ${bblue}$(brew list | wc -l | tr -d ' ')"
echo "   ${white}.5@Y ;  :@@P555B@@@P             "                                                          
echo "     ${white}5@G?J!J@B!:  ^G5J^             " "${BG_WHITE}     ${RESET}${BG_MAGENTA}     ${RESET}${BG_RED}     ${RESET}${BG_YELLOW}     ${RESET}${BG_BLUE}     ${RESET}${BG_CYAN}     ${RESET}${BG_GREEN}     ${RESET}${BG_BLACK}     ${RESET}"                                                  
echo "     ${white}~PB#&@BJ~^:                    " "${BG_BWHITE}     ${RESET}${BG_BMAGENTA}     ${RESET}${BG_BRED}     ${RESET}${BG_BYELLOW}     ${RESET}${BG_BBLUE}     ${RESET}${BG_BCYAN}     ${RESET}${BG_BGREEN}     ${RESET}${BG_BBLACK}     ${RESET}"                                                                
echo "       ${white}...7.                        "                                                     
echo "                              "
# Color variables with background colors
BG_BLACK="\033[0;40m"
BG_RED="\033[0;41m"
BG_GREEN="\033[0;42m"
BG_YELLOW="\033[0;43m"
BG_BLUE="\033[0;44m"
BG_MAGENTA="\033[0;45m"
BG_CYAN="\033[0;46m"
BG_WHITE="\033[0;47m"
BG_BBLACK="\033[0;100m"
BG_BRED="\033[0;101m"
BG_BGREEN="\033[0;102m"
BG_BYELLOW="\033[0;103m"
BG_BBLUE="\033[0;104m"
BG_BMAGENTA="\033[0;105m"
BG_BCYAN="\033[0;106m"
BG_BWHITE="\033[0;107m"
RESET="\033[0m"
# Color variables with foreground colors
black=" \u001b[30m"
red=" \u001b[31m"
green=" \u001b[32m"
yellow=" \u001b[33m"
blue=" \u001b[34m"
magenta=" \u001b[35m"
cyan=" \u001b[36m"
white=" \u001b[37m"
reset=" \u001b[0m"
bblack="\u001b[90;1m"
bred="\u001b[91;1m"
bgreen="\u001b[92;1m"
byellow="\u001b[93;1m"
bblue="\u001b[94;1m"
bmagenta="\u001b[95;1m"
bcyan="\u001b[96;1m"
bwhite="\u001b[97;1m"
reset="\u001b[0m"